### ISSUE TITLE
Unexpected behavior of '$' as anchor

### ISSUE THREAD

**Issue by nelsonhf** [lonekorean/regex-storm#1]
- Test strings:
`Game`
`FunAndGames`
`MiddleGame`
`GameTaste`
`LastGame`
- Regular Expression:
`Game$`
- Comments:
I think it should match lines 1, 3, and 5, in multiline mode; it only matches 5 and that only if this line does not end with a newline.
If the RegEx is `^Game`, it will match 1 and 4 in multiline and 1 in non-multiline (as I expect).
As far as I can tell, `$` is behaving exactly like `\Z`, independent of the flags used.
I tested the behavior in Chrome, Firefox and Internet Explorer.

**Comment by lonekorean** [comment]
This is one of those weird edge cases where the web interface itself affects the matching. Browsers actually insert 2 characters when you hit enter in a textarea: \r\n. It's the \r that throws off the regex.

Here's a modified pattern that probably gives you what you're looking for: http://regexstorm.net/tester?p=Game%5cr%3f%24&i=Game%0d%0aFunAndGames%0d%0aMiddleGame%0d%0aGameTaste%0d%0aLastGame&o=m

Personally, I've found that \r creeps up in various cases, so I usually craft my regex to optionally accept it when appropriate.

**Comment by nelsonhf** [comment]
Thanks for replying! And the permalink is a great thing, too!
That's one of the beauties of browsers: too many of them, each doing its own
thing.
Thanks for the help and advice!  





On Fri, Apr 28, 2017 8:53 PM, Will Boyd notifications@github.com  wrote:
This is one of those weird edge cases where the web interface itself affects the
matching. Browsers actually insert 2 characters when you hit enter in a
textarea: \r\n. It's the \r that throws off the regex.

Here's a modified pattern that probably gives you what you're looking for: 
http://regexstorm.net/tester?p=Game%5cr%3f%24&i=Game%0d%0aFunAndGames%0d%0aMiddleGame%0d%0aGameTaste%0d%0aLastGame&o=m

Personally, I've found that \r creeps up in various cases, so I usually craft my
regex to optionally accept it when appropriate.
