### ISSUE TITLE
Domain name lost

### ISSUE THREAD

**Issue by nloum** [lonekorean/regex-storm#8]
There's something wrong with the website. When I go to http://regexstorm.net/ I see the following message:
<img width="1064" alt="Screen Shot 2021-12-29 at 2 39 39 PM" src="https://user-images.githubusercontent.com/39776302/147701666-49016e38-3a0d-4309-abf4-6b70c5ed1f23.png">

**Comment by lonekorean** [comment]
Hey thanks for the heads up. Yeah my domain name totally expired. 🤦‍♂️ I renewed, should be back online now.

Thanks for telling me before it became a really expensive mistake.

**Comment by lonekorean** [comment]
(it might take a bit to propagate to everyone)
